apiVersion: v1
kind: Service

metadata:
  name: docker-kubernetes-lab-service

spec:
  selector:
    app: docker-kubernetes-lab

  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

  type: ClusterIP